
name: msa-data

# 네트워크 선언
# - 서비스 compose(docker-compose.service.yml)와 컨테이너끼리 통신하려면
#   동일한 네트워크를 사용해야 한다. 그 공용 네트워크를 여기선 만든다.
# - 이 파일이 네트워크의 주인이다. 그래서 data를 반드시 먼저 실행해야(up) 한다.
networks:
  msa-network:
    name: msa-network

services:
  mysql:
    # Docker Hub 공식 MySQL 이미지
    image: mysql:9.4
    container_name: mysql

    # 컨테이너가 시작될 때 실행할 명령어
    # 서버 기본 문자셋
    # - MySQL 이미지의 기본 클라이언트 문자셋이 latin1이라, 이걸 지정하지 않으면
    #   db/*.sql 의 한글이 깨친 채로 저장된다.
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    # 컨테이너 안으로 전달될 환경변수
    environment:
      # root 계정 비밀번호
      MYSQL_ROOT_PASSWORD: 1234
    
    # 포트매핑 "호스트포트:컨테이너포트"
    # - 컨테이너 내부 MySQL은 3306에서 동작
    # - 호스트(내 PC)에서 3307로 접속 -> 컨테이너 내부 3306으로 접속
    ports:
      - "3307:3306"
    
    volumes:
      - ./db:/dcoker-entrypoint-initdb.d:ro
      - mysql-data:/var/lib/mysql

      

# named volume 선언
# - named volume은 컨테이너가 삭제되어도 데이터가 유지된다.
volumes:
  mysql-data: {}
